package audioManager;

public enum Choice {
    EXIT,
    ADD_AUDIO,
    REMOVE_AUDIO,
    DISPLAY_FILELIST,
    CLEAR_FILELIST,
    TOTAL_MEDIAFILES,
    SAVE_FILESLIST,
    SAVE_AUDIO,
    SAVE_VIDEO,
//    LOAD_FILESLIST,
    LOAD_VIDEO,
    LOAD_AUDIO,
    ADD_VIDEO,
    REMOVE_VIDEO,
    AUDIOFILE,
    VIDEOFILE,
    SEARCH,
    START_MENU,
    ERROR;
}

